name: Validate

on:
  pull_request:
    types:
      - review_requested

  push:
    branches:
      - 'main'

concurrency:
  group: validate-${{ github.ref_name }}
  cancel-in-progress: true

env:
  CAIDO_NODE_VERSION: 20
  CAIDO_PNPM_VERSION: 9

jobs:
  typecheck:
    name: 'Typecheck'
    runs-on: ubuntu-latest
    if: ${{ !github.event.pull_request.draft }}
    timeout-minutes: 10

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.CAIDO_NODE_VERSION }}

      - name: Setup pnpm
        uses: pnpm/action-setup@v3.0.0
        with:
          version: ${{ env.CAIDO_PNPM_VERSION }}

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run typechecker
        run: pnpm typecheck